### ISSUE TITLE
Adding commands in multiple places

### ISSUE THREAD

**Issue by czechboy0** [kylef/Commander#25]
I'm struggling with using Curassow, because it's using Commander for input arguments. I'd like to add my own arguments and parse my app's specific ones only, and leave Curassow to parse its own as well. Unfortunately currently Commander errors out if any command is unused, making this usecase impossible. 

Assuming I'm not missing anything, I'd like there to be an option to *not* error out when unrecognized arguments are passed, instead they'd be ignored, making multi-layer argument parsing possible.

**Comment by kylef** [comment]
I think this is going to be problematic when the arguments clash, i-e, both tools offer a `-b`, `--help` etc, and makes it difficult to show intuitive help. It would also make it difficult to determine unhandled arguments and raise an error if a user tries to use an option or subcommand that does not exist.

I'd propose that Curassow provides an API that you can use to serve instead of using the command line interface, so you're free to add whatever handling you want. How does this sound?

**Comment by czechboy0** [comment]
You're right, that's definitely a better way to do it. Let me know when there's an issue on Curassow that I can track, thanks!

**Comment by kylef** [comment]
Perhaps it makes sense to go into https://github.com/kylef/Curassow/issues/12. That way, you can make an instance of the arbiter and run it.

```swift
let arbiter = Arbiter<SyncronousWorker>(workers: 3, addresses: [], timeout: 20, application: app)
try arbiter.run()
```

**Comment by czechboy0** [comment]
Hmm that's fair, but I really like how I didn't have to worry about such details with `server`. Maybe just add another overloaded version of `serve`, which will take those three parameters, in addition to the application? And then make the current `serve` run Commander and pass the params into the new one? That way I can just use the non-CLI version of `serve`, and I still don't touch the implementation details (as much anyway) of Curassow?
