### ISSUE TITLE
Are optional options available?

### ISSUE THREAD

**Issue by jorge-ramirez** [kylef/Commander#69]
I just started using Commander and it is awesome.  I just had one question.  Are options with optional values available?  What I would like is to have an option that if the user did not specify that option with a value on the command line, I would like to receive nil for that option's value.

I see that the `default` parameter for the `Option` class is not optional.  In my use case, there is no possible default value.  If the user specifies a value, I add it to the service call's query parameter, if not, it is omitted.  When I try something like this:

```
Option<String?>("campaign", default: nil, description: "The campaign identifier used to narrow the search."),
```

I get the following error:

```
Type 'String?' does not conform to protocol 'ArgumentConvertible'
```

Is there currently anyway to do this using Commander?

**Comment by adamkaplan** [comment]
You could try to extend `Optional<String>` like this, as I did:
```
extension Optional: ArgumentConvertible where Wrapped == String {
    public init(parser: ArgumentParser) throws { ... }
}
```

But a problem with arise: the `ArgumentConvertible` protocol defines a non-failable convenience initializer. All Optional constructors are inherently failable because they create optionals... which is logical. Therefore if you try to just call `self.init("val")` in the body, it will complain about a non-failable initializer designating to a failable initializer, which is obviously disallowed.

So, no, it is not possible.

Command should really support optional defaults because there are plenty of cases where there is a difference between "not set" and "empty". This forces integrators to add custom sentinel values as default values, like `default: ""`, and check for those values later. That is basically the same as an Optional, right?

**Comment by finestructure** [comment]
To add to that, and that took me a moment to figure out: If your "optional Option" isn't of type `String?` but any other `ArgumentConvertible`, say `Int?`, you'll need to write the `init` differently:

```
extension Optional: ArgumentConvertible where Wrapped: ArgumentConvertible {
    public init(parser: ArgumentParser) throws {
        if let parser = parser.shift().map({ ArgumentParser(arguments: [$0]) }) {
            self = try Wrapped(parser: parser)
        } else {
            self = .none
        }
    }
}
```

This works for `String?` as well, so this is a more general variant.
